auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from . import views as myviews


app_name = 'auth'
urlpatterns = [
    url(r'^login/$', myviews.MyLoginView.as_view(), name='login'),
    url(r'^logout/$', myviews.MyLogoutView.as_view(), name='logout'),

    url(r'^password_change/$', views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='homepage'),
    url(r'^(?P<pk>\d+)/detail/$', views.blog_detail, name='blog_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_blog, name='edit_blog'),
    url(r'^create/$', views.create_blog, name='create_blog'),
    url(r'^draft/$', views.DraftBlog.as_view(), name='draft_blog'),
    url(r'^private/$', views.PrivateBlog.as_view(), name='private_blog'),
    url(r'^myblog/$', views.MyBlog.as_view(), name='my_blog'),
    url(r'^blogger/$', views.UserList.as_view(), name='blogger'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("blog.urls")),
    url(r'^profile/', include("my_auth.urls")),
]
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.shortcuts import reverse

# default_user_id = 1 default=default_user_id,
# Create your models here.
class MyPost(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    tags = models.CharField(max_length=20, null=True, blank=True)
    published_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(default=timezone.now)
    is_draft = models.BooleanField(default=False)
    is_private = models.BooleanField(default=False)
    can_be_edited = models.BooleanField(default=False)
    allow_comment = models.BooleanField(default=True)

    class Meta:
        ordering = ['published_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[str(self.id)])


class PostComment(models.Model):
    pass

blog/forms/blog_form.py
from django import forms
from django.forms import ModelForm
from blog.models import MyPost

class BlogForm(ModelForm):
    class Meta:
        model = MyPost
        fields = ['title','tags','content','published_time','created_time']
        localized_fields = ('published_time','created_time')

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from django.contrib.auth import decorators as auth_decorators
from django.views.generic import ListView
from . import models
from .forms.blog_form import BlogForm
from my_auth.models import User
from .utils import my_paginator_style
from django.contrib.auth.mixins import LoginRequiredMixin


class MyPaginatedBlogListView(ListView):
    model = models.MyPost
    paginate_by = 5
    context_object_name = 'blog_list'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        queryset = self.get_queryset()
        paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, self.get_paginate_by(queryset))
        # add the page numbers to be shown in homepage to context
        context = my_paginator_style(paginator, page, context, pages_num_2b_shown=5)
        return context


class UserList(MyPaginatedBlogListView):
    model = User
    template_name = 'blog/blogger_list.html'
    context_object_name = 'blogger_list'

    def get_queryset(self):
        return User.objects.all().order_by('username')


class HomePage(MyPaginatedBlogListView):
    model = models.MyPost
    template_name = 'blog/homepage.html'
    paginate_by = 5
    context_object_name = 'blog_list'

    def get_queryset(self):
        return models.MyPost.objects.filter(is_draft=False, is_private=False).order_by('-published_time')


class MyBlog(LoginRequiredMixin, MyPaginatedBlogListView):
    model = models.MyPost
    login_url = 'auth:login'
    template_name = 'blog/my_blog_list.html'
    paginate_by = 5
    context_object_name = 'blog_list'

    def get_queryset(self):
        return models.MyPost.objects.filter(author__username=self.request.user.username,
                                              is_draft=False, is_private=False).order_by('-published_time')


class DraftBlog(LoginRequiredMixin, MyPaginatedBlogListView):
    model = models.MyPost
    login_url = 'auth:login'
    template_name = 'blog/draft_list.html'
    paginate_by = 5
    context_object_name = 'blog_list'

    def get_queryset(self):
        return models.MyPost.objects.filter(author__username=self.request.user.username,
                                              is_draft=True, is_private=False).order_by('-published_time')


class PrivateBlog(LoginRequiredMixin, MyPaginatedBlogListView):
    model = models.MyPost
    login_url = 'auth:login'
    template_name = 'blog/private_list.html'
    paginate_by = 5
    context_object_name = 'blog_list'

    def get_queryset(self):
        return models.MyPost.objects.filter(author__username=self.request.user.username,
                                                is_draft=False, is_private=True).order_by('-published_time')


def blog_detail(request, pk):
    blog_instance = get_object_or_404(models.MyPost, pk=pk)

    # need to add permission to protect draft blog and private blog

    template_name = 'blog/blog_detail.html'
    if blog_instance.author.username == request.user.username or request.user.is_superuser:
        blog_instance.can_be_edited = True
    context = {
        'blog': blog_instance,
    }
    return render(request, template_name, context)


@auth_decorators.login_required(login_url = 'auth:login')
def edit_blog(request,pk):
    blog_instance = get_object_or_404(models.MyPost, pk=pk)
    template_name = 'blog/edit_blog.html'
    context = {}
    # if request user is the owner of the blog
    if blog_instance.author.username == request.user.username or request.user.is_superuser:
        if request.method == "POST":
            blog_edit_form = BlogForm(request.POST)
            if blog_edit_form.is_valid():
                blog_cd = blog_edit_form.cleaned_data
                blog_instance.title, blog_instance.tags, blog_instance.content, blog_instance.published_time, blog_instance.created_time \
                    = blog_cd['title'], blog_cd['tags'], blog_cd['content'], blog_cd['published_time'], blog_cd['created_time']
                print('save_as_draft' in request.POST, 'publish' in request.POST)
                if 'save_as_draft' in request.POST:
                    blog_instance.is_draft = True
                elif 'publish' in request.POST:
                    blog_instance.is_draft = False
                blog_instance.save()
                return HttpResponseRedirect(reverse('blog:blog_detail', args=(blog_instance.id,)))
        else:
            blog_form = BlogForm(initial={
                'title': blog_instance.title,
                'tags': blog_instance.tags,
                'content': blog_instance.content,
                'published_time': blog_instance.published_time,
                'created_time': blog_instance.created_time,
            })
            context['blog_form'] = blog_form
            return render(request, template_name, context)
    else:
        context['permission_error'] = True
        template_name = 'registration/permission_denied.html'
        return render(request, template_name, context)


@auth_decorators.login_required(login_url = 'auth:login')
def create_blog(request):
    template_name = 'blog/create_blog.html'
    context = {}
    if request.method == 'POST':
        # print('if')
        new_blog_form = BlogForm(request.POST)
        # print(new_blog_form.is_valid())
        if new_blog_form.is_valid():
            new_blog_cd = new_blog_form.cleaned_data
            new_blog = models.MyPost.objects.create(author=request.user, **new_blog_cd)
            # print(request.user)
            if 'save_as_draft' in request.POST:
                new_blog.is_draft = True
            elif 'Publish' in request.POST:
                new_blog.is_draft = False
            #print(new_blog.is_draft)
            new_blog.save()
            return HttpResponseRedirect(reverse('blog:blog_detail', args=(new_blog.id,)))
    else:
        #print('else')
        new_blog_form = BlogForm()
        context['blog_form'] = new_blog_form
        return render(request,template_name, context)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load blog_tag %}
{% load static %}
<head>

  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}">
</head>

<body>

  <div class="container-fluid">
    <div class="row content">
      {% block sidebar %}
      <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
      </br></br></br>
          <li class=""><a href="{% url 'blog:homepage' %}">Home</a></li>
          <li><a href="{% url 'blog:blogger' %}">All bloggers</a></li>
          {% if user.is_authenticated %}
                <li><a href="{% url 'blog:create_blog' %}">Write a Blog</a></li>
                <li><a href="">My Profile</a></li>
                <li><a href="{% url 'blog:my_blog' %}">My Blog</a></li>
                <li><a href="{% url 'blog:draft_blog' %}">Draft</a></li>
                <li><a href="{% url 'blog:private_blog' %}">Private Blog</a></li>
                <li><a href="">Welcome {{ user.first_name }} {{ user.last_name }}</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
          {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
          {% endif %}
      </ul>
      {% endblock %}
      </div>

    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
    </div>
  </div>
</body>
</html>

blog/templates/blog/blog_detail.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}
<head>
    {% block title %}
        <title>{{ blog.title }}</title>
    {% endblock %}

</head>

<body>

{% block content %}
    <h2 id="center">{{ blog.title }}</h2>
    <h5 id=""><span class="glyphicon glyphicon-time"></span> Posted by {% real_name_or_username blog %}, {{ blog.published_time }}.</h5>
    <h5 id=""><span class="label label-primary">{{ blog.tags }}</span></h5>

    {% if blog.can_be_edited %}
        <h5><button type="button" class="btn"><a href="{% url 'blog:edit_blog' blog.id %}">Edit blog</a></button>
            <button type="button" class="btn"><a href="">Delete blog</a></button></h5></br>
    {% endif %}
    <p>{{ blog.content|linebreaks }}</p>

{% endblock %}
</body>
</html>

blog/templates/blog/blog_form.html
<!DOCTYPE html>
<html lang="en">
{% load blog_tag %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<form action="" class="" method="post">
    {% csrf_token %}
    <div class="fieldWrapper">
        {{ blog_form.title.errors }}
        {{ blog_form.title.label_tag }}
        {{ blog_form.title|addclass:"blog_title" }}
    </div>

    <div class="fieldWrapper">
        {{ blog_form.title.errors }}
        {{ blog_form.tags.label_tag }}
        {{ blog_form.tags|addclass:"blog_tags" }}
    </div>

    <div class="fieldWrapper">
        {{ blog_form.content.errors }}
        {{ blog_form.content.label_tag }}
        {{ blog_form.content|addclass:"blog_content" }}
    </div>

    <div class="row">
    <div class="fieldWrapper">
        {{ blog_form.published_time.errors }}
        {{ blog_form.published_time.label_tag }}
        {{ blog_form.published_time|addclass:"blog_published_time" }}
    </div>

     <div class="fieldWrapper">
         {{ blog_form.created_time.errors }}
         {{ blog_form.created_time.label_tag }}
         {{ blog_form.created_time|addclass:"blog_created_time" }}
    </div>
    </div>

    <button class="btn btn-primary" name="publish">Publish</button>
    <button class="btn btn-primary" name="save_as_draft">Save Draft</button>

</form>

</body>
</html>

blog/templates/blog/blogger_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}

{% block title %}
    <title>{{ blog.title }}</title>
{% endblock %}


{% block content %}
    </br></br></br></br>

    <h1>All Bloggers in This Site</h1>
    {% if blogger_list %}
        {% for blogger in blogger_list %}
            <li><a href="">{{ blogger.username }}</a></li>
        {% endfor %}
    {% else %}
    <p>No bloggers are found</p>
    {% endif %}

    {% include "blog/pagination.html" %}

{% endblock %}

</html>

blog/templates/blog/create_blog.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}


<head>
    {% block title %}
        <title>New Blog</title>
    {% endblock %}
</head>

<body>
{% block content %}
    {% if form.errors %}
        <p>
            Please correct the error{{ form.error|pluralize }} below.
        </p>
    {% endif %}

<h2>Compose New Blog</h2>

{% include "blog/blog_form.html" %}

{% endblock %}
</body>
</html>

blog/templates/blog/draft_list.html
<!DOCTYPE html>
<html lang="en">

{% extends 'blog/base.html' %}
{% load blog_tag %}

{% block title %}
    <title>Drafts</title>
{% endblock %}

{% block content %}
</br></br></br></br>
<h1>{{ user.username|title }}'s Drafts</h1>
{% if blog_list %}
    {% for blog in blog_list %}
        <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{ blog.published_time }})
            -------{% real_name_or_username blog %}</li>
    {% endfor %}
{% else %}
    <p>No blogs are found</p>
{% endif %}
{% include "blog/pagination.html" %}
{% endblock %}

</html>

blog/templates/blog/edit_blog.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}

<head>
{% block title %}
    <title>{{ blog.title }}</title>
{% endblock %}
</head>

<body>

{% block content %}
    {% if form.errors %}
        <p>
            Please correct the error{{ form.error|pluralize }} below.
        </p>
    {% endif %}
    <h2>Edit Blog</h2>
    {% include "blog/blog_form.html" %}
{% endblock %}

</body>
</html>

blog/templates/blog/homepage.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}

    <h1 class="center">All Posted Blogs</h1>
    {% if blog_list %}
        {% for blog in blog_list %}
            <h2><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h2>
            <h5><span class="glyphicon glyphicon-time"></span> Posted by {% real_name_or_username blog %}, {{ blog.published_time }}.</h5>
            <h5><span class="label label-primary">{{ blog.tags }}</span></h5><br>
            <p>{{ blog.content|linebreaks }}</p>

        {% endfor %}
    {% else %}
        <p>No blogs are found</p>
    {% endif %}
    {% include "blog/pagination.html" %}
{% endblock %}

</html>

blog/templates/blog/my_blog_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}

{% block title %}
    <title>My Blog</title>
{% endblock %}

{% block content %}
</br></br></br></br>
<h1>{{ user.username|title }}'s Blogs</h1>
{% if blog_list %}
    {% for blog in blog_list %}
        <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{ blog.published_time }})
            -------{% real_name_or_username blog %}</li>
    {% endfor %}
{% else %}
    <p>No blogs are found</p>
{% endif %}
{% include "blog/pagination.html" %}
{% endblock %}

</html>

blog/templates/blog/pagination.html
<!DOCTYPE html>
<html lang="en">
{% load blog_tag %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    {% if is_paginated %}
        {% if multiple_page_series_to_show %}
            {% if page_obj.has_previous %}
                <button type="button" class="btn"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></button>
            {% endif %}
            {% for i in page_number_to_be_show %}
                {% if page_obj.number == i %}
                    <button type="button" class="btn">{{ i }}</button>
                {% else %}
                    <button type="button" class="btn"><a  href="?page={{ i }}">{{ i }}</a></button>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <button type="button" class="btn"><a href="?page={{ page_obj.next_page_number }}">Next</a></button>
            {% endif %}
        {% else %}
            {% if page_obj.has_previous %}
                <button type="button" class="btn"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></button>
            {% endif %}
            {% for page_number in paginator.page_range %}
                {% if page_obj.number == page_number %}
                    {{ page_number }}
                {% else %}
                    <button type="button" class="btn"><a href="?page={{ page_number }}">{{ page_number }}</a></button>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                    <button type="button" class="btn"><a href="?page={{ page_obj.next_page_number }}">Next</a></button>
            {% endif %}
        {% endif %}
    {% endif %}
</body>
</html>

blog/templates/blog/private_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'blog/base.html' %}
{% load blog_tag %}

{% block title %}
    <title>My Private Blog</title>
{% endblock %}

{% block content %}
</br></br></br></br>

<h1>{{ user.username|title }}'s Private Blogs</h1>
{% if blog_list %}
    {% for blog in blog_list %}
        <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>({{ blog.published_time }})
            -------{% real_name_or_username blog %}</li>
    {% endfor %}
{% else %}
    <p>No blogs are found</p>
{% endif %}
{% include "blog/pagination.html" %}
{% endblock %}

</html>